name: CD

on:
  workflow_run:
    workflows: ["CI"]       
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }} 

      - name: Deploy stack on VM
        shell: bash
        run: |
          REPO_NAME="***-labo0"
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} " \
            cd ~
            if [ ! -d '$REPO_NAME' ]; then 
              git clone git@github.com:suzyao/***-labo0.git;
            fi 
            cd '$REPO_NAME'
            git fetch --all --prune
            git checkout main || git checkout master 
            git pull --ff-only
            docker compose build --no-cache 
            docker compose up -d --remove-orphans 
            docker image prune -f 
            docker compose ps 
          "
          

