name: CD

on:
  workflow_run:
    workflows: ["CI"]       
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }} 

      - name: Deploy stack on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
          set -euo pipefail

          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          cd ~
          if [ ! -d "$REPO_NAME" ]; then
            git clone https://github.com/$GITHUB_REPOSITORY.git
          fi
          cd "$REPO_NAME"

          git fetch --all --prune
          git checkout main
          git pull --ff-only

          docker compose build --no-cache
          docker compose up -d --remove-orphans

          docker image prune -f

          docker compose ps
          EOF
